# Generated by Django 3.1.2 on 2020-10-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201021_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.PositiveIntegerField(default=50),
            preserve_default=False,
        ),
    ]
