# Generated by Django 3.1.2 on 2020-10-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201022_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='status',
        ),
    ]
