# Generated by Django 3.1.2 on 2020-10-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_remove_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
