# Generated by Django 3.1.2 on 2020-10-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.PositiveIntegerField(),
        ),
    ]
